services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
    env_file:
      - .env
    command: ['yarn', 'dev']

  mongo:
    # latest mongo db image
    image: mongo:latest
    ports:
      - '27017:27017'
