# for production
services:
  nginx:
    ports:
      - '80:80'
  node-app:
    build:
      context: .
      # set args to install only production dependencies
      args:
        NODE_ENV: production
    environment:
      - MONGO_IP=${MONGO_IP}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PORT=${REDIS_PORT}
      - SESSION_SECRET=${SESSION_SECRET}
    command: ['yarn', 'start']
