# for production
services:
  nginx:
    ports:
      - '80:80'
  node-app:
    build:
      context: .
      # set args to install only production dependencies
      args:
        NODE_ENV: production
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    command: ['yarn', 'start']
