# list all container required
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  # start node-app
  node-app:
    # build docker image from docker file
    build: .
    # set environment value required by image
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    # latest mongo db image
    image: mongo:latest
    # set environment value required by image
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    # set volumes to persist data
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

# list all named volumes
volumes:
  mongo-db:
